#!/bin/bash

polybar -r &
nitrogen --restore &

# Set decoration geometry
berryc border_width       5
berryc inner_border_width 0
berryc title_height      25
berryc top_gap            0
berryc edge_gap  0 37 0 0

# Set decoration colors
berryc focus_color         A67E5B
berryc unfocus_color       292D3E
berryc inner_focus_color   59523C
berryc inner_unfocus_color 565679
berryc text_focus_color    D8D9CC
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "MesloLGS Nerd Font Mono"
